// Extracts the game-icons.net silhouettes Delve uses into src/icons.gen.ts.
//
// Source: @iconify-json/game-icons (the full set as JSON). Only the icons
// listed here are copied, so the bundle carries a few dozen paths rather than
// four thousand. Authors come from scripts/authors.txt, a listing of the
// upstream repo (github.com/game-icons/icons, <author>/<icon>.svg), because
// CC BY 3.0 wants each icon credited to its artist.

import { readFileSync, writeFileSync } from 'node:fs'

const WANT = `
visored-helm hooded-assassin wizard-face sun-priest robin-hood-hat barbarian
rat goblin-head skeleton evil-bat slime bandit long-legged-spider shambling-zombie spotted-mushroom venus-flytrap
orc-head direwolf hyena-head cultist harpy mimic-chest lizardman floating-ghost mummy-head scorpion snake bear-head kenku-head
ogre troll minotaur werewolf vampire-cape medusa-head hooded-figure rock-golem wyvern
vampire-dracula skull-staff hydra horned-skull spiked-dragon-head ice-golem metal-golem-head black-knight-helm
goblin crowned-skull masked-spider dragon-head triple-skulls imp
wolf-head dwarf-face woman-elf-face barn-owl imp-laugh fairy swordwoman monk-face nun-face golem-head cat
open-treasure-chest locked-chest crystal-shrine star-altar shop campfire wolf-trap stairs wooden-door scroll-unfurled
dead-head progression dice-twenty-faces-twenty crossed-swords
health-potion magic-potion round-potion standing-potion potion-of-madness tied-scroll broadsword two-handed-sword
round-shield chest-armor ring power-ring torc skeleton-key
`.trim().split(/\s+/)

const set = JSON.parse(readFileSync(new URL('../node_modules/@iconify-json/game-icons/icons.json', import.meta.url), 'utf8'))
const authors = new Map(
  readFileSync(new URL('./authors.txt', import.meta.url), 'utf8')
    .split(/\r?\n/)
    .filter(Boolean)
    .map(p => {
      const [author, file] = p.split('/')
      return [file.replace(/\.svg$/, ''), author]
    }),
)

const icons = {}
const credits = {}
for (const name of WANT) {
  const icon = set.icons[name]
  if (!icon) throw new Error(`no icon ${name}`)
  const paths = [...icon.body.matchAll(/\sd="([^"]+)"/g)].map(m => m[1])
  if (!paths.length) throw new Error(`no paths in ${name}`)
  icons[name] = { w: icon.width ?? set.width ?? 512, h: icon.height ?? set.height ?? 512, d: paths }
  credits[name] = authors.get(name) ?? 'unknown'
}

const out = `// Generated by scripts/build-icons.mjs -- do not edit.
// Icons from game-icons.net, CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/).
// Each icon's artist is listed in ICON_AUTHORS.

export type IconName = ${WANT.map(n => `'${n}'`).join(' | ')}

export const ICONS: Record<IconName, { w: number; h: number; d: string[] }> = ${JSON.stringify(icons)}

export const ICON_AUTHORS: Record<IconName, string> = ${JSON.stringify(credits, null, 1)}
`
writeFileSync(new URL('../src/icons.gen.ts', import.meta.url), out)
const missing = Object.entries(credits).filter(([, a]) => a === 'unknown').map(([n]) => n)
console.log(`${WANT.length} icons, ${(out.length / 1024).toFixed(0)} KB${missing.length ? `; no author for ${missing.join(', ')}` : ''}`)
